### PR TITLE
Fix navigation for small screens

### PR DESCRIPTION
**Pull request by susnux**

### CODE REVIEW

**Comment by susnux** [comment]
@zjedi sorry for the inconvenience, this fixes the problem you mentioned.

**Comment by susnux** [comment]
(the flex was only needed for the small screens, on large screens the flex direction should be column not row)

**Comment by zjedi** [comment]
> @zjedi sorry for the inconvenience, this fixes the problem you mentioned.

no problem, thanks for the fix!

**Comment by zjedi** [comment]
@susnux The top menu for smaller screen is not left-aligned, is that intentional? It used to be centered like the content itself.

**Pull request merged**
