### PR TITLE
Add ability to reference icons in external links

### PR DESCRIPTION
**Pull request by ottlinger**
Add new parameter to external links to reference and print icons in front of external links.

### CODE REVIEW

**Comment by ottlinger** [comment]
@zjedi not sure if there is a nicer (more Go-like) way to reference/call the other shortcode, but copy&paste works locally.

**Comment by zjedi** [comment]
This looks very useful, thanks for contributing!

> @zjedi not sure if there is a nicer (more Go-like) way to reference/call the other shortcode, but copy&paste works locally.
As long as it works it's fine in my eyes :) You can have look at https://gohugo.io/templates/shortcode-templates/ for more details on custom shortcodes.

The only imperfection in my eyes is having the space between icon and text underlined - but that would complicate the implementation, not a big deal :)
image

**Comment by ottlinger** [comment]
@zjedi I've added the space as the icon is glued to the text otherwise. Would you think a &nbsp; would be a better solution? Thanks.

**Comment by zjedi** [comment]
One can alternatively use extlink and icon separately, if it's not required to have the icon linkeable

**Pull request merged**
